"""empty message

Revision ID: 4def2acc9fe3
Revises: 239f7540e94b
Create Date: 2020-10-30 21:08:48.305136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4def2acc9fe3'
down_revision = '239f7540e94b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
