"""empty message

Revision ID: 586806682e39
Revises: 
Create Date: 2020-11-03 18:03:24.322160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '586806682e39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'map_coords', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'map_coords', type_='unique')
    # ### end Alembic commands ###
