"""empty message

Revision ID: bc1ee451f9da
Revises: 01c4a9d33fb3
Create Date: 2020-11-03 07:56:46.799170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc1ee451f9da'
down_revision = '01c4a9d33fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'moto_coords', ['moto_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'moto_coords', type_='unique')
    # ### end Alembic commands ###
