"""empty message

Revision ID: 2f6e413875da
Revises: b9befa10dd04
Create Date: 2020-11-15 23:01:18.680562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f6e413875da'
down_revision = 'b9befa10dd04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rentals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('moto_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('book_hour', sa.String(), nullable=False),
    sa.Column('finish_book_hour', sa.String(), nullable=False),
    sa.Column('finish_rental_hour', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['moto_id'], ['motos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rentals')
    # ### end Alembic commands ###
